server:
  port: 8081
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: product-service
  boot:
    admin:
      client:
        url: http://localhost:1111/
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

        
management:
  endpoints:
    web:
      exposure:
        include: "*"